// Generated by Apple Swift version 4.0 effective-3.2 (swiftlang-900.0.65 clang-900.0.37)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import CoreDataStack;
@import CoreNetworkStack;
@import Foundation;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("WebServiceKit")
@class HttpWebRequest;
@protocol ProgressListener;

SWIFT_PROTOCOL_NAMED("RequestQueue")
@protocol RequestQueue
- (void)enqueueRequest:(HttpWebRequest * _Nonnull)capsul;
- (void)enqueueRequest:(HttpWebRequest * _Nonnull)capsul progressListener:(id <ProgressListener> _Nullable)progressListener;
- (BOOL)cancelable:(HttpWebRequest * _Nonnull)capsul SWIFT_WARN_UNUSED_RESULT;
- (void)cancelRequest:(HttpWebRequest * _Nonnull)capsul;
@end


SWIFT_CLASS_NAMED("BaseRequestQueue")
@interface BaseRequestQueue : NSObject <RequestQueue>
- (void)enqueueRequest:(HttpWebRequest * _Nonnull)capsul;
- (void)enqueueRequest:(HttpWebRequest * _Nonnull)capsul progressListener:(id <ProgressListener> _Nullable)progressListener;
- (BOOL)cancelable:(HttpWebRequest * _Nonnull)capsul SWIFT_WARN_UNUSED_RESULT;
- (void)cancelRequest:(HttpWebRequest * _Nonnull)capsul;
- (void)kickStart;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class ContentHandler;
@class NSCoder;

SWIFT_CLASS_NAMED("ContentDelegateImpl")
@interface ContentDelegateImpl : NGObject <ContentDelegate>
- (void)progressHandler:(ContentHandler * _Null_unspecified)handler didFailedWithError:(NSError * _Null_unspecified)error;
- (void)progressHandler:(ContentHandler * _Null_unspecified)handler uploadPercentage:(float)percentage;
- (void)progressHandler:(ContentHandler * _Null_unspecified)handler downloadPercentage:(float)percentage;
- (null_unspecified instancetype)initWithInfo:(NSDictionary * _Null_unspecified)info OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithJSON:(NSData * _Null_unspecified)json OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// 👉 Don’t use use PersistableSynchronizer(or any subclass) from background thread.
/// this class is not thread safe. Calling from other then Main Thread might causes crash.
SWIFT_CLASS_NAMED("SavableRequestQueue")
@interface SavableRequestQueue : BaseRequestQueue
@end


/// 👉 Don’t use use PersistableSynchronizer(or any subclass) from background thread.
/// this class is not thread safe. Calling from other then Main Thread might causes crash.
SWIFT_CLASS_NAMED("DownloadQueue")
@interface DownloadQueue : SavableRequestQueue
@end

@class NSString;

SWIFT_CLASS("_TtC13WebServiceKit10FieldError")
@interface FieldError : NGObject
@property (nonatomic, strong) NSString * _Nullable objectName;
@property (nonatomic, strong) NSString * _Nullable field;
@property (nonatomic, strong) NSString * _Nullable message;
- (null_unspecified instancetype)initWithInfo:(NSDictionary * _Null_unspecified)info OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithJSON:(NSData * _Null_unspecified)json OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, HttpStatusCode, "HttpStatusCode") {
  HttpStatusCodeOk = 200,
  HttpStatusCodeCreated = 201,
  HttpStatusCodeBadRequest = 400,
  HttpStatusCodeUnauthorized = 401,
  HttpStatusCodePaymentRequired = 402,
  HttpStatusCodeForbidden = 403,
  HttpStatusCodeNotFound = 404,
  HttpStatusCodeMethodNotAllowed = 405,
  HttpStatusCodeNotAcceptable = 406,
  HttpStatusCodePoxyAuthRequired = 407,
  HttpStatusCodeRequestTimeout = 408,
  HttpStatusCodeInternalServerError = 500,
  HttpStatusCodeNotImplemented = 501,
  HttpStatusCodeBadGateway = 502,
  HttpStatusCodeServiceUnavailable = 503,
  HttpStatusCodeGatewayTimeout = 504,
  HttpStatusCodeHttpVersionNotSupported = 505,
};


SWIFT_PROTOCOL_NAMED("ProgressListener")
@protocol ProgressListener
- (void)progressUpdate:(CGFloat)value;
@optional
- (void)progressStart;
- (void)progressEnd;
@end

@class RequestMetadata;

SWIFT_CLASS_NAMED("RequestFactory")
@interface RequestFactory : NSObject
- (nonnull instancetype)initWithConfigFileName:(NSString * _Nonnull)fileName OBJC_DESIGNATED_INITIALIZER;
- (void)updateProperty:(id _Nonnull)value forKey:(NSString * _Nonnull)key;
- (id _Nonnull)getPropertyForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)httpReferrerHeaderValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isLiveUrlActive SWIFT_WARN_UNUSED_RESULT;
- (NSURL * _Nonnull)activeURL SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)activeURLString SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)pingURLString SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)validateUrlStr:(NSString * _Nonnull)urlStr SWIFT_WARN_UNUSED_RESULT;
- (RequestMetadata * _Nullable)metadataForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSURL * _Nullable)requestURLForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (HttpWebRequest * _Nullable)requestForKey:(NSString * _Nonnull)key classType:(SWIFT_METATYPE(HttpWebRequest) _Nonnull)classType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("RequestMetadata")
@interface RequestMetadata : NGObject
- (void)updateValue:(id _Null_unspecified)value forKey:(NSString * _Null_unspecified)key;
- (id _Null_unspecified)serializeValue:(id _Null_unspecified)value forKey:(NSString * _Null_unspecified)key SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithInfo:(NSDictionary * _Null_unspecified)info OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithJSON:(NSData * _Null_unspecified)json OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13WebServiceKit16RequestProcessor")
@interface RequestProcessor : NSObject
- (void)start;
- (void)abort;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS_NAMED("RequestQueueConfiguration")
@interface RequestQueueConfiguration : NGObject
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithInfo:(NSDictionary * _Null_unspecified)info SWIFT_UNAVAILABLE;
- (null_unspecified instancetype)initWithJSON:(NSData * _Null_unspecified)json SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSError;

SWIFT_PROTOCOL_NAMED("RequestQueueDelegate")
@protocol RequestQueueDelegate
- (void)synchronizationSucceed:(HttpWebRequest * _Nullable)forRequest incomming:(NSData * _Nonnull)incomming;
- (void)synchronizationFailed:(HttpWebRequest * _Nullable)forRequest error:(NSError * _Nullable)error;
@optional
- (void)downloadSucceed:(HttpWebRequest * _Nullable)forRequest saveUrl:(NSURL * _Nonnull)saveUrl;
- (id <ProgressListener> _Nonnull)progressListener:(HttpWebRequest * _Nullable)forRequest SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("Response")
@interface Response : NGObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithInfo:(NSDictionary * _Null_unspecified)info OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) NSObject * _Nonnull id;
@property (nonatomic, readonly) BOOL failed;
@property (nonatomic) enum HttpStatusCode code;
@property (nonatomic, strong) NSString * _Nullable error;
@property (nonatomic, strong) NSString * _Nullable error_description;
@property (nonatomic, strong) NSString * _Nullable errorMessage;
@property (nonatomic, strong) NSString * _Nullable message;
@property (nonatomic, copy) NSArray<FieldError *> * _Nonnull fieldErrors;
- (void)updateValue:(id _Null_unspecified)value forKey:(NSString * _Null_unspecified)key;
- (null_unspecified instancetype)initWithJSON:(NSData * _Null_unspecified)json SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS_NAMED("Tracker")
@interface Tracker : NGObject
- (void)updateValue:(id _Null_unspecified)value forKey:(NSString * _Null_unspecified)key;
- (id _Null_unspecified)serializeValue:(id _Null_unspecified)value forKey:(NSString * _Null_unspecified)key SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithInfo:(NSDictionary * _Null_unspecified)info OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithJSON:(NSData * _Null_unspecified)json OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13WebServiceKit11Transaction")
@interface Transaction : NSObject
- (nonnull instancetype)initWithRequest:(HttpWebRequest * _Nonnull)request parserType:(SWIFT_METATYPE(Response) _Nonnull)parserType memoryHandler:(NSDictionary<NSString *, id> * _Nonnull (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))memoryHandler OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull (^ _Nonnull workingMemoryHandler)(NSDictionary<NSString *, id> * _Nonnull);
@property (nonatomic) SWIFT_METATYPE(Response) _Nonnull parserType;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull workingMemory;
- (void)addObjectToMemory:(id _Nonnull)value key:(NSString * _Nonnull)key;
- (void)copyObjectFromMemory:(NSDictionary<NSString *, id> * _Nonnull)memory key:(NSString * _Nonnull)key;
- (void)copyAll:(NSDictionary<NSString *, id> * _Nonnull)from;
@property (nonatomic, strong) HttpWebRequest * _Nonnull request;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@protocol NGObjectProtocol;

SWIFT_CLASS("_TtC13WebServiceKit16TransactionStack")
@interface TransactionStack : NSObject
- (nonnull instancetype)initWithCallBack:(void (^ _Nullable)(NSArray<id <NGObjectProtocol>> * _Nullable))callBack OBJC_DESIGNATED_INITIALIZER;
- (void)commit;
- (void)cancel;
- (void)processingDidFinished:(RequestProcessor * _Nonnull)processor finalResponse:(NSArray<id <NGObjectProtocol>> * _Nullable)finalResponse;
- (void)processingDidFailed:(RequestProcessor * _Nonnull)processor failedResponse:(id <NGObjectProtocol> _Nonnull)failedResponse;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// 👉 Don’t use PersistableSynchronizer(or any subclass) from background thread.
/// this class is not thread safe. Calling from other then Main Thread might causes crash.
SWIFT_CLASS_NAMED("UploadQueue")
@interface UploadQueue : SavableRequestQueue
@end


/// 👉 Don’t use PersistableSynchronizer(or any subclass) from background thread.
/// this class is not thread safe. Calling from other then Main Thread might causes crash.
SWIFT_CLASS_NAMED("UploadOnceQueue")
@interface UploadOnceQueue : UploadQueue
@end


SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
